### ISSUE TITLE
.contributor-block does not link to anywhere

### ISSUE THREAD

**Issue by Primata** [movement-network/movement-hack#33]
![image](https://github.com/movemntdev/movement-hack/assets/6299375/57fa498d-dce2-4234-bb36-a7aa1e16b52a)
https://movement-hack.netlify.app/week_2/testing

There are two sections where issue is present, Manual testing and For movement
https://movement-hack.netlify.app/week_2/testing#manual-testing
https://movement-hack.netlify.app/week_2/testing#for-movement

**Comment by l-monninger** [comment]
Will replace these shortly.
